site_name: Help - Clock.sh
nav:
    - Home: index.md
    - Notification: Notification.md
    - About: about.md
    - Usecases: usecases.md
    - "Interact with Other Services": services.md
theme:
  name: 'material'
